#include "key.h"

#include "prefs.h"

pkeystruct key[] = {
    {"MAGNITUDE", P_STRING, &prefs.magname, 0, 0, 0.0, 0.0, {""}, 0, 1, NULL, 0},
    {"LENSMAGNITUDE", P_STRING, &prefs.lensmagname, 0, 0, 0.0, 0.0, {""}, 0, 1, NULL, 0},
    {"NMAG", P_INT, &prefs.nelem, 0, 99, 0.0, 0.0, {""}, 0, 1, NULL, 0},
    {"MAGNITUDE_ONLY", P_BOOL, &prefs.magonly, 0, 0, 0.0, 0.0, {""}, 0, 0, NULL, 0},
    {"SIZE", P_STRING, &prefs.sname, 0, 0, 0.0, 0.0, {""}, 0, 1, NULL, 0},
    {"LENSSIZE", P_STRING, &prefs.lenssname, 0, 0, 0.0, 0.0, {""}, 0, 1, NULL, 0},
    {"SMINMAG", P_FLOAT, &prefs.sminmag, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"SREFMAG", P_FLOAT, &prefs.srefmag, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"SMAXMAG", P_FLOAT, &prefs.smaxmag, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"INSEEING", P_FLOAT, &prefs.inseeing, 0, 2, 0, BIG, {""}, 0, 1, NULL, 0},
    {"OUTSEEING", P_FLOAT, &prefs.outseeing, 0, 2, 0, BIG, {""}, 0, 1, NULL, 0},
    {"XI_0", P_FLOAT, &prefs.xi_0, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"XI_1", P_FLOAT, &prefs.xi_1, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"XI_2", P_FLOAT, &prefs.xi_2, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"XI_3", P_FLOAT, &prefs.xi_3, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"XI_4", P_FLOAT, &prefs.xi_4, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"ALPHA_0", P_FLOAT, &prefs.alpha_0, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"ALPHA_1", P_FLOAT, &prefs.alpha_1, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"ALPHA_2", P_FLOAT, &prefs.alpha_2, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"ALPHA_3", P_FLOAT, &prefs.alpha_3, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"ALPHA_4", P_FLOAT, &prefs.alpha_4, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"KAPPA_0", P_FLOAT, &prefs.kappa_0, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"KAPPA_1", P_FLOAT, &prefs.kappa_1, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"KAPPA_2", P_FLOAT, &prefs.kappa_2, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"KAPPA_3", P_FLOAT, &prefs.kappa_3, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"KAPPA_4", P_FLOAT, &prefs.kappa_4, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"ELLIPTICITY", P_STRING, &prefs.ename, 0, 0, 0.0, 0.0, {""}, 0, 1, NULL, 0},    
    {"SHEAR", P_STRING, &prefs.shearname, 0, 0, 0.0, 0.0, {""}, 0, 1, NULL, 0},
    {"EMINMAG", P_FLOAT, &prefs.eminmag, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"EREFMAG", P_FLOAT, &prefs.erefmag, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"EMAXMAG", P_FLOAT, &prefs.emaxmag, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"EPSMAX", P_FLOAT, &prefs.epsmax, 0, 0, 0, 100, {""}, 0, 1, NULL, 0},
    {"P_0", P_FLOAT, &prefs.p_0, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"P_1", P_FLOAT, &prefs.p_1, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"P_2", P_FLOAT, &prefs.p_2, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"P_3", P_FLOAT, &prefs.p_3, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"SIGMA_0", P_FLOAT, &prefs.sigma_0, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"SIGMA_1", P_FLOAT, &prefs.sigma_1, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"SIGMA_2", P_FLOAT, &prefs.sigma_2, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"SIGMA_3", P_FLOAT, &prefs.sigma_3, 0, 0, -BIG, BIG, {""}, 0, 1, NULL, 0},
    {"VERBOSE", P_INT, &prefs.verbose, 0, 5, 0.0, 0.0, {""}, 0, 1, NULL, 0},
    {"SEED", P_INT, &prefs.seed, 0, 999999999, 0.0, 0.0, {""}, 0, 1, NULL, 0},
    {"NTHREADS", P_INT, &prefs.nthreads, 0, 512, 0.0, 0.0, {""}, 0, 1, NULL, 0},
    {"", 0, NULL, 0, 0, 0.0, 0.0, {""}, 0, 1, NULL, 0}
};


char                    keylist[sizeof(key)/sizeof(pkeystruct)][16];
const char              notokstr[] = {" \t=,;\n\r\""};


char *default_prefs[] = {
    "# Default configuration file for mockshapes",
    "# JPD 12.01.2010",
    "#",
    "#---------------------------- Input Catalog ------------------------------------",
    "MAGNITUDE     TMAG        # Column name for magnitude",
    "LENSMAGNITUDE LMAG        # Column name for lensed magnitude",
    "NMAG          3           # Position of magnitude in vector",
    "MAGNITUDE_ONLY N          # Set to Y if no shapes/sizes in catalog",
    " ",
    "#---------------------------- Size Parameters ----------------------------------",
    "SIZE          TSIZE       # Name of intrinsic (true) size column in output", 
    "LENSSIZE      OSIZE       # Name of observed (magnified) object size",
    "SMINMAG       17.5        # Minimum valid magnitude of polynomial fit",
    "SREFMAG       22.0        # Reference magnitude of polynomial fit",
    "SMAXMAG       26.24       # Maximum valid magnitude of polynomial fit",
    "INSEEING      0.635       # Seeing in which the model parameters were measured",
    "OUTSEEING     0.9         # Seeing of the output catalog",
    "XI_0          0.676538    # Parameters for 4th order polynomial fit to xi",
    "XI_1          -0.0597809  #",
    "XI_2          -0.00242377 #",
    "XI_3          -0.00276862 #",
    "XI_4          0.000889298 #",
    "ALPHA_0       0.175922    # Parameters for 4th order polynomial fit to alpha",
    "ALPHA_1       -0.0172894  #",
    "ALPHA_2       -0.00162605 #",
    "ALPHA_3       -0.00233168 #",
    "ALPHA_4       0.000617415 #",
    "KAPPA_0       -0.658123   # Parameters for 4th order polynomial fit to kapp",
    "KAPPA_1       -0.00185666 #",
    "KAPPA_2       0.0318665   #",
    "KAPPA_3       0.0010374   #",
    "KAPPA_4       -0.00132519 #",
    " ",
    "#--------------------------- Shape Parameters ----------------------------------",
    "ELLIPTICITY   TE          # Name of ellipticity column in output",
    "SHEAR         EPSILON     # Name of the observed shear estimator",
    "EMINMAG       21.38       # Minimum valid magnitude of polynomial fit",
    "EREFMAG       24.0        # Reference magnitude of polynomial fit",
    "EMAXMAG       26.81       # Maximum valid magnitude of polynomial fit",
    "EPSMAX        1.0         # Maximum ellipticity",
    "SIGMA_0       0.2679      # Parameters for cubic polynomial fit to sigma_p",
    "SIGMA_1       0.0415      #",
    "SIGMA_2       0.0010      #",
    "SIGMA_3       -0.0010     #",
    "P_0           1.2565      # Parameters for cubic polynomial fit to p",
    "P_1           0.0937      #",
    "P_2           -0.0049     #",
    "P_3           -0.0029     #",
    " ",
    "#---------------------------- Program Setup ------------------------------------",
    "VERBOSE       4           # Verbosity of output",
    "SEED          0           # Random number seed",
    "NTHREADS      0           # Number of OpenMP threads (0: use system default)",
    ""
};

